### ISSUE TITLE
Getting Status Code 500 with PyU4V.utils

### ISSUE THREAD

**Issue by sumang99** [dell/powermax-splunk-addon#3]
**I was trying to upgrade TA-DellEMC_VMAX from 2.0.9 to 3.0.0 which started to give me below Error on a Fresh install and also upgrade. I have Python 3.7 running on the server with Splunk Version 8.1.5. Can you explain why I'm see the below error? Are we required manually install  PyU4V along with the libraries wrapped in the TA?** 

2022-03-03 15:01:27,990 ERROR pid=21599 tid=MainThread file=base_modinput.py:log_error:309 | Get error when collecting events.
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/py_lib_dir/aob_py3/modinput_wrapper/base_modinput.py", line 128, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/inputs.py", line 265, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/powermax_splunk_core/driver/powermax_input_module.py", line 47, in collect_events
    pmax = PMaxSplunk(helper=helper, event_writer=ew)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/powermax_splunk_core/driver/powermax_splunk.py", line 41, in __init__
    self.conn = self._establish_pyu4v_connection()
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/powermax_splunk_core/driver/powermax_splunk.py", line 78, in _establish_pyu4v_connection
    application_type='Splunk-{}'.format(pc.VERSION))
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/py_lib_dir/aob_py3/PyU4V/PyU4V/univmax_conn.py", line 128, in __init__
    self.validate_unisphere()
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/py_lib_dir/aob_py3/PyU4V/PyU4V/univmax_conn.py", line 162, in validate_unisphere
    uni_ver, major_ver = self.common.get_uni_version()
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/py_lib_dir/aob_py3/PyU4V/PyU4V/common.py", line 589, in get_uni_version
    response = self.get_resource(category=VERSION, no_version=True)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/py_lib_dir/aob_py3/PyU4V/PyU4V/common.py", line 376, in get_resource
    target_uri, resource_type, kwargs.get('params'))
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/py_lib_dir/aob_py3/PyU4V/PyU4V/common.py", line 349, in get_request
    self.check_status_code_success(operation, sc, message)
  File "/opt/splunk/etc/apps/TA-DellEMC_VMAX/bin/py_lib_dir/aob_py3/PyU4V/PyU4V/common.py", line 183, in check_status_code_success
    data=exception_message)
PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error GET None. The status code received is 500 and the message is {'message': 'The server encountered an unexpected condition which prevented it from fulfilling the request'}.

**Comment by sumang99** [comment]
Looks like my issue is related to Unisphere version.
Array u-code at level: 5978.711.711
Unisphere: v9.0.2.10

**Comment by sheehp3** [comment]
Closed as stale issue resolved by user
